services:
  db:
    image: postgres:15-alpine
    container_name: rifa-db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rifa-network

  backend:
    build: ./backend
    container_name: rifa-backend
    restart: always
    depends_on:
      - db
    environment:
      - PROJECT_NAME=${PROJECT_NAME}
      - API_V1_STR=${API_V1_STR}
      - SECRET_KEY=${SECRET_KEY}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
      - POSTGRES_SERVER=${POSTGRES_SERVER}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - FIRST_SUPERUSER=${FIRST_SUPERUSER}
      - FIRST_SUPERUSER_PASSWORD=${FIRST_SUPERUSER_PASSWORD}
      - BACKEND_CORS_ORIGINS=${BACKEND_CORS_ORIGINS}
    ports:
      - "8010:8000"
    networks:
      - rifa-network

  frontend:
    build:
      context: ./frontend
      # args:
        # VITE_API_URL: /api/v1
    container_name: rifa-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "8090:80"
    networks:
      - rifa-network

volumes:
  postgres_data:

networks:
  rifa-network:
    driver: bridge
