version: '3.8'

services:
  backend_rifas:
    build: ./backend
    container_name: backend_rifas
    ports:
      - "8800:8000"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  frontend_rifas:
    build: ./frontend
    container_name: frontend_rifas
    ports:
      - "8801:5173"
    env_file:
      - .env
    environment:
      - VITE_API_URL=http://localhost:8800/api/v1
    depends_on:
      - backend_rifas
    restart: unless-stopped
